# tasks file for Install-Docker

# Install Docker On Ubuntu

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  when: ansible_facts['distribution'] == "Ubuntu"


- name: Install dependencies
  ansible.builtin.apt:
    name: "{{ item }}" 
    state: present
  loop:
     - ca-certificates
     - curl
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Docker using official script
  ansible.builtin.shell: curl -fsSL https://get.docker.com | sh
  become: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Install Docker Compose plugin
  ansible.builtin.shell: |
    mkdir -p /usr/libexec/docker/cli-plugins/
    curl -SL https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-linux-x86_64 -o /usr/libexec/docker/cli-plugins/docker-compose
    chmod +x /usr/libexec/docker/cli-plugins/docker-compose
  become: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Start and enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  when: ansible_facts['distribution'] == "Ubuntu"


# ------------------------------------------------------------------------------

# Install Docker On RedHat


- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name: dnf-plugins-core
    state: present
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
  

- name: Add Docker repository
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  become: yes
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_facts['os_family'] == "RedHat"


- name: Install docker on Redhat
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
     - docker-ce
     - docker-ce-cli
     - containerd.io
     - docker-buildx-plugin
     - docker-compose-plugin
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable and start Docker service on RedHat
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
  when: ansible_facts['os_family'] == "RedHat"
